export const columns = [
  {
    title: 'No.',
    width: 40,
    align: 'center',
    dataIndex: 'id',
    key: 'id',
    render: (text: any, record: API.StationInfo, index: number) => index + 1,
  },
  {
    title: '轨道',
    width: 50,
    align: 'center',
    dataIndex: 'nLane',
    key: 'nLane',
  },
  {
    title: '站位',
    width: 50,
    align: 'center',
    dataIndex: 'station',
    key: 'station',
  },
  {
    title: '槽位',
    width: 50,
    align: 'center',
    dataIndex: 'slot',
    key: 'slot',
  },
  {
    title: '子槽位',
    width: 60,
    align: 'center',
    dataIndex: 'subSlot',
    key: 'subSlot',
  },
  {
    title: '料号',
    width: 150,
    dataIndex: 'compName',
    key: 'compName',
  },
  {
    title: '料盘',
    width: 200,
    dataIndex: 'compId',
    ellipsis: true,
    key: 'compId',
  },
];
